// Code generated by mockery v2.14.0. DO NOT EDIT.

package reply

import mock "github.com/stretchr/testify/mock"

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// CreateReplyReply provides a mock function with given fields: data, userId, replyId
func (_m *MockRepository) CreateReplyReply(data *Domain, userId int, replyId int) (Domain, error) {
	ret := _m.Called(data, userId, replyId)

	var r0 Domain
	if rf, ok := ret.Get(0).(func(*Domain, int, int) Domain); ok {
		r0 = rf(data, userId, replyId)
	} else {
		r0 = ret.Get(0).(Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*Domain, int, int) error); ok {
		r1 = rf(data, userId, replyId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateReplyThread provides a mock function with given fields: data, userId, threadId
func (_m *MockRepository) CreateReplyThread(data *Domain, userId int, threadId int) (Domain, error) {
	ret := _m.Called(data, userId, threadId)

	var r0 Domain
	if rf, ok := ret.Get(0).(func(*Domain, int, int) Domain); ok {
		r0 = rf(data, userId, threadId)
	} else {
		r0 = ret.Get(0).(Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*Domain, int, int) error); ok {
		r1 = rf(data, userId, threadId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteReply provides a mock function with given fields: userId, replyId
func (_m *MockRepository) DeleteReply(userId int, replyId int) error {
	ret := _m.Called(userId, replyId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(userId, replyId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditReply provides a mock function with given fields: data, userId, replyId
func (_m *MockRepository) EditReply(data *Domain, userId int, replyId int) (Domain, error) {
	ret := _m.Called(data, userId, replyId)

	var r0 Domain
	if rf, ok := ret.Get(0).(func(*Domain, int, int) Domain); ok {
		r0 = rf(data, userId, replyId)
	} else {
		r0 = ret.Get(0).(Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*Domain, int, int) error); ok {
		r1 = rf(data, userId, replyId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReplyByID provides a mock function with given fields: replyId, limit
func (_m *MockRepository) GetReplyByID(replyId int, limit int) (Domain, error) {
	ret := _m.Called(replyId, limit)

	var r0 Domain
	if rf, ok := ret.Get(0).(func(int, int) Domain); ok {
		r0 = rf(replyId, limit)
	} else {
		r0 = ret.Get(0).(Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(replyId, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReplyByThreadID provides a mock function with given fields: threadId, limit, offset
func (_m *MockRepository) GetReplyByThreadID(threadId int, limit int, offset int) ([]Domain, error) {
	ret := _m.Called(threadId, limit, offset)

	var r0 []Domain
	if rf, ok := ret.Get(0).(func(int, int, int) []Domain); ok {
		r0 = rf(threadId, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(threadId, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReplyChilds provides a mock function with given fields: replyId, limit, offset
func (_m *MockRepository) GetReplyChilds(replyId int, limit int, offset int) ([]Domain, error) {
	ret := _m.Called(replyId, limit, offset)

	var r0 []Domain
	if rf, ok := ret.Get(0).(func(int, int, int) []Domain); ok {
		r0 = rf(replyId, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(replyId, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Like provides a mock function with given fields: userId, replyId
func (_m *MockRepository) Like(userId int, replyId int) error {
	ret := _m.Called(userId, replyId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(userId, replyId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UndoLike provides a mock function with given fields: userId, replyId
func (_m *MockRepository) UndoLike(userId int, replyId int) error {
	ret := _m.Called(userId, replyId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(userId, replyId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UndoUnlike provides a mock function with given fields: userId, replyId
func (_m *MockRepository) UndoUnlike(userId int, replyId int) error {
	ret := _m.Called(userId, replyId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(userId, replyId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Unlike provides a mock function with given fields: userId, replyId
func (_m *MockRepository) Unlike(userId int, replyId int) error {
	ret := _m.Called(userId, replyId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(userId, replyId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRepository(t mockConstructorTestingTNewMockRepository) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
