// Code generated by mockery v2.14.0. DO NOT EDIT.

package verify

import mock "github.com/stretchr/testify/mock"

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// DeleteVerifyData provides a mock function with given fields: email
func (_m *MockRepository) DeleteVerifyData(email string) error {
	ret := _m.Called(email)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchVerifyData provides a mock function with given fields: email
func (_m *MockRepository) FetchVerifyData(email string) (Domain, error) {
	ret := _m.Called(email)

	var r0 Domain
	if rf, ok := ret.Get(0).(func(string) Domain); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreVerifyData provides a mock function with given fields: data
func (_m *MockRepository) StoreVerifyData(data Domain) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(Domain) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRepository(t mockConstructorTestingTNewMockRepository) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
