name: Railway Deploy

on:
  push:
    branches: [dev]
   
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Generate certificate from secrets
        run: echo "${{ secrets.BASE64_CERT }}" | base64 --decode > ca.pem && mv ca.pem app/ca.pem

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
